# Generated by Django 4.1.5 on 2023-04-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_post_like'),
        ('Exercises', '0001_initial'),
        ('Plans', '0002_serie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Set',
        ),
    ]
