# Generated by Django 4.1.5 on 2023-04-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0003_rename_serie_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
