# Generated by Django 4.1.5 on 2023-04-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0004_set_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='set',
            name='plan',
        ),
        migrations.AddField(
            model_name='set',
            name='exercise_to_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Plans.exercisetoplan'),
            preserve_default=False,
        ),
    ]
