# Generated by Django 4.1.5 on 2023-04-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetoplan',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercisetoplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='author',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseToPlan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
