# Generated by Django 4.1.5 on 2023-03-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='owner',
        ),
        migrations.AddField(
            model_name='friends',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile'),
            preserve_default=False,
        ),
    ]
