# Generated by Django 4.1.5 on 2023-03-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_friends_friend_alter_friends_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='owner',
        ),
        migrations.AddField(
            model_name='friends',
            name='current_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='Accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='RequestFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to='Accounts.profile')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to='Accounts.profile')),
            ],
        ),
    ]
