# Generated by Django 4.1.5 on 2023-03-19 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_friends_owner_friends_current_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfriends',
            name='sent',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
