# Generated by Django 4.1.5 on 2023-04-02 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='current_user',
        ),
        migrations.AddField(
            model_name='friends',
            name='me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='me', to='Accounts.profile'),
            preserve_default=False,
        ),
    ]
