# Generated by Django 4.1.5 on 2023-04-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_friends_current_user_friends_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='me',
        ),
        migrations.AddField(
            model_name='friends',
            name='current_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='Accounts.profile'),
            preserve_default=False,
        ),
    ]
