# Generated by Django 4.1.5 on 2023-04-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_remove_friends_me_friends_current_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Post',
        ),
    ]
