# Generated by Django 4.1.5 on 2023-04-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
