# Generated by Django 4.1.5 on 2023-04-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('muscle', models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'ABS'), (2, 'BACK'), (3, 'BISEPSC'), (4, 'CARDIO'), (5, 'CHEST'), (6, 'GLUTES'), (7, 'LEGS'), (8, 'SHOULDERS'), (9, 'TRICPES')], default=0)),
            ],
        ),
    ]
